// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVvi0LsyEyVPib2dKpih5msZ6aU7VRU7w',
    appId: '1:389249704236:web:08e707e2e53dc3c7878c89',
    messagingSenderId: '389249704236',
    projectId: 'converterapp-de568',
    authDomain: 'converterapp-de568.firebaseapp.com',
    storageBucket: 'converterapp-de568.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpTsx02lofpUbmZvbWSIMrZgP877JXl04',
    appId: '1:389249704236:android:d7fb4da14c21639c878c89',
    messagingSenderId: '389249704236',
    projectId: 'converterapp-de568',
    storageBucket: 'converterapp-de568.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuXbiCAV-iW6TFhH3yWleoejQMX7oSB7k',
    appId: '1:389249704236:ios:9798dead2ba43e89878c89',
    messagingSenderId: '389249704236',
    projectId: 'converterapp-de568',
    storageBucket: 'converterapp-de568.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuXbiCAV-iW6TFhH3yWleoejQMX7oSB7k',
    appId: '1:389249704236:ios:e684fd39eb165ac9878c89',
    messagingSenderId: '389249704236',
    projectId: 'converterapp-de568',
    storageBucket: 'converterapp-de568.appspot.com',
    iosBundleId: 'com.example.flutterApplication3.RunnerTests',
  );
}
